### ISSUE TITLE
Update your repo you coward

### ISSUE THREAD

**Issue by witcheslive** [th3j35t3r/CounterSocial#1]
You are in violation of the AGPL. Update your repo. This is not the currently running version of Mastodon software at counter.social.

The AGPL stipulates that you provide the source for network services that you are running with modified versions of AGPL software, such as Mastodon, publicly and for free.

**Comment by x-Code-x** [comment]
Could you please point to the specific Clause of AGPL v 3.0 that the repo is in violation of?
Note that underlying network infrastructure, nor modules or plugins that utilise the OStatus or ActivityPub to communicate with the Mastadon source is not covered under the AGPL. 
At best, the source code you are viewing is out of step with Mastadon core. I believe that Clause 5 has not currently been breached, but if you can show demonstrated evidence, a maintainer will of course update the relevant notices.

**Comment by th3j35t3r** [comment]
^^^ Woot - Someone who know the AGPL - Kudos!

**Comment by witcheslive** [comment]
The current version of counter.social is obviously not running off of this repo, the AGPL does not stipulate that you need to put your dumbass firewall rules or payment gateways for COSOPRO or whatever like you like to pretend is this huge thing or that anyone actually wants, but it does stipulate that the modifications you made to the AGPL software to hook into those things need to be published, and I sure don't see anything such as, for instance, the verbiage indicating certain features are COSOPRO only in this repo.

**Comment by x-Code-x** [comment]
Hi there.

Firstly, please be polite - I am simply another Github user and have no beef with you, much as I may take being called Jesters sock puppet account as a compliment.

While your concerns are valid, if counter.social is not running off this repo as you observe, then I fail to see how the AGPL in this repo requires updating to include covering functionality that this fork and version doesn't contain.

If it is the repo which is currently powering counter.social, then using terms such as "obviously" is disingenuous - the additional features currently found on counter.social may in fact (as I suspect is the case, given they appear to have been implemented as security features in the underlying network configuration first, then surfaced as features on the site later) be hooking in to existing unmodified functionality provided by the Mastadon fork and leveraging of the OStatus protocol and standard making counter.social proper, at best, an aggregate work.

Again, should you respond, I would ask you as a fellow Github member to keep your comments respectful and on point. Should you not respond, or cannot provide additional supporting evidence, or a pull request with updated wording for the license with documented/commented reasons for collaborative discussion inorser to resolve the issue, I will recommend to the repo owner that this issue be marked closed.

**Comment by witcheslive** [comment]
Oh shut up with your respectability bullshit, Jester. Follow the fucking AGPL. You have made modifications to counter.social that exist within the scope of the Mastodon code you ripped off, and those need to be published. You have obviously made modifications within the last year and a half or whatever since you've updated this repo, and they need to be published. There is no "when it's finished" with network code. If you are providing network services with modified AGPL code, you need to publish those modifications in a public location and for free. That's the terms of the AGPL. It's not that complicated. I do it. It's not hard, in fact it makes it a lot easier to run witches.live. 

And hey maybe if you do this you'll learned how to do difficult computer concepts like "merge from upstream" so C.S. isn't running on some shitheap version of glitchsoc from like 2011 and you aren't ripping off people who buy COSOPRO as badly.

**Comment by x-Code-x** [comment]
I recommend this issue now be closed as complete.

**Comment by x-Code-x** [comment]
Oh, and OP - I said that earlier, not Jester... and I am a much much different creature to J. I did ask you to be respectful - I have no beef with you. I'm just another GitHub user. And please, don't mistake my "respectability" for anything but diplomacy - that's my skill set and I'm sure you know the definition of diplomacy, as they say.

**Comment by witcheslive** [comment]
13. Remote Network Interaction; Use with the GNU General Public License.

Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. This Corresponding Source shall include the Corresponding Source for any work covered by version 3 of the GNU General Public License that is incorporated pursuant to the following paragraph.

Notwithstanding any other provision of this License, you have permission to link or combine any covered work with a work licensed under version 3 of the GNU General Public License into a single combined work, and to convey the resulting work. The terms of this License will continue to apply to the part which is the covered work, but the work with which it is combined will remain governed by version 3 of the GNU General Public License.

**Comment by witcheslive** [comment]
cat got your tongue?

**Comment by sascha-sl** [comment]
Any code that runs in the same process as the original piece of software - that being mastodon's backend, sidekiq processing and streaming server - must be published back when available over a network.

This has clearly not happened and I'd recommend this repository to be updated as soon as possible for counter.social to be compliant with the license that it acquired the rights to use the original source code with.

**Comment by witcheslive** [comment]
Making it clear again that the mastodon repo on this account, which can be found at https://github.com/witcheslive/mastodon , is yet another example of complying with the AGPL. Not only is it what you agree to when you make modifications to AGPL code, it also makes deployments much easier and helps strengthen the community of Mastodon admins who can help each other make modifications they need or offer mutual aid in debugging and troubleshooting issues with particular deployments.

It was particularly useful last night when I was trying to help berries.space, which is yet another example of a Mastodon instance running a modified version of Mastodon that complies with the AGPL by posting its full and current source and uses the github repo to aid in deployment, solve an issue that was making the instance unavailable for a large number of users.

**Comment by witcheslive** [comment]
saw you finally learned how to clumsily merge in 2.8, you gonna update your repo yet? blobcatsip

**Comment by Andynowacki** [comment]
"Update your repo you coward #1" Is this how you open a dialogue with people by calling them cowards and then you wonder why your interactions with people aren't to your liking.

These are your own (rules) and I'm assuming your own TOS on your Mastodon instance:
https://witches.live/about/more

3) Treat your fellow witches with the utmost respect, and be respectful in how you deal with those on other instances. Of course you may cast dunking hexes on chuds, but please don't interfere with the technical workings of other instances, post "dox," or participate in abuse or harassment campaigns.

No users from counter.social were even aware of your instance before you openly began attacking people. If you have an issue with AGLP I'd suggest you take that issue to the Mastodon. 

It would be better if people could show some decency on the internet but it seems like you are incapable of this with respect to your previous communications and threats from your own instance.

If you feel this is a potential legal issue I would recommend seeking legal advice

I would also advise that the github platform is an inappropriate platform for these kind of grievances to be voiced in a professional manner.

Regards

**Comment by witcheslive** [comment]
@Andynowacki 

> "Update your repo you coward #1" Is this how you open a dialogue with people by calling them cowards and then you wonder why your interactions with people aren't to your liking.

I didn't wonder shit, stop assuming anything about me, weirdo.

Yes those are my rules. Jester is a chud and I'm casting a dunking hex on him. Deal with it.

I already cited the relevant section of the AGPL, not the AGLP, which isn't a thing as far as I know. Please learn to read and write before being a sniveling, bootlicking weirdo at me. Moreover, github is THE place to bring up a grievance with someone breaking the law involving the source cdoe that they stole, because it is where the source code should be published.

Please go learn to read, then review this section of the AGPL that I already posted again, then you can go back to the boot section of the Docker store to find more lollipops:


  

13. Remote Network Interaction; Use with the GNU General Public License.

> Notwithstanding any other provision of this License, if you modify the Program, your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge, through some standard or customary means of facilitating copying of software. This Corresponding Source shall include the Corresponding Source for any work covered by version 3 of the GNU General Public License that is incorporated pursuant to the following paragraph.

> Notwithstanding any other provision of this License, you have permission to link or combine any covered work with a work licensed under version 3 of the GNU General Public License into a single combined work, and to convey the resulting work. The terms of this License will continue to apply to the part which is the covered work, but the work with which it is combined will remain governed by version 3 of the GNU General Public License.

**Comment by Andynowacki** [comment]
Focus and ask again

**Comment by x-Code-x** [comment]
@witcheslive @aurelia-sl 
Sorry for the delayed reply - cat hadn't got my tongue - I've been busy - RL and go-live releases and all that.

Look. Personally my (kinda extensive) AGPL experience has focused around software used by government. I'd like to single out CKAN (https://github.com/ckan/ckan) in particular - the product that powers a large amount of the Open Data and Open Government platforms across the world governments (especially those tending towards socialist democracies). I can assure you, beyond a skerrik of a doubt, that there is not a government on the planet, nor large enterprises involved in the same scale of online communication/data, that are publishing their network or security configurations, infrastructure code etc. None.

(I also took a look at witches.live and the SerenityLabs fork. Certainly for witches, @witcheslive you said you made modifications (ie forked) and then reshared your source. a) Your source links direct to Mastadon master and b) it has no network or security configs... same with Serenity @aurelia-sl - I couldn't on a quick scan see anything deeper than nginx configs - certainly nothing for the network/infrastructure layer which is where the "features" Mastadon originally took umbrage with reside, as far as I have been able to ascertain from my own research. Even the "3rd party app" redirect on the front of the site is nothing more than a basic 302 which hardly counts as modification.)

What's the real issue here? The not exact compliance with licensing? Or the underlying politics you and others seem to have with Jester?

**Comment by aurelia-sl** [comment]
Everything that runs in _the same process_ counts as modification.

We don't publish nginx config, and nobody asked for them either. That's a strawman.

There are some very clear modifications on counter.social to the Mastodon (not Mastadon) core. This includes things like simple menu changes. 

We actually [do change the Git URL](https://github.com/SerenityLaboratories/mastodon/blob/sl/config/initializers/serenitylabs.rb) too.

**Comment by witcheslive** [comment]
@x-Code-x the hell is wrong with you. governments comply with the AGPL too, and the jester is a private citizen no matter how much he larps as a cop. i didn't ask for jester's firewall rules, i don't know why you basic males think that firewall configuration is part of the source code for an application, but males arent known for their computer prowess i guess.

if you fork an AGPL software package you have to release the modifications you made to the agpl code. stop making excuses like little weenie babies and do the right thing. don't you faux-hard wannabe cop types always go around saying shit like "no excuses"? well no excuses. follow the agpl.

**Comment by Andynowacki** [comment]
Can't say now

**Comment by c0d3murd3r** [comment]
@witcheslive It's likely time to give up your sjw/radicalized triggered-behavior.  If @th3j35t3r wants to fork and rebuild, that's his business.  Clause 5 has not been breached as @x-Code-x has mentioned.

Furthermore, you're not qualified nor educated enough on IP and Software licensing to be giving soapbox speeches on what you feel someone should and shouldn't do.  

Focus on running your instance and promoting a positive spirit in the community.  If CoSo decides to make changes to the underlying infrastructure or configurations, that's their business and should not be of concern to you.

And while we're on the topic.  I've hard forked and completely rewritten the architecture to focus on darknets.  Are you going to chase me and my team down to with your broom? 

Play nice... we are.  And learn CoC for Github.

**Comment by witcheslive** [comment]
@c0d3murd3r lmao no it is not "his business" he is breaking the law you fucking dweeb

the code of conduct on github is follow software licences. so follow software licences and stop making excuses. its funny you and jester hate trump so much when you sound exactly like him

**Comment by aurelia-sl** [comment]
I'd like to note for the record, that _even gab dot fucking com_ managed to send me a copy of their fork on request, which makes you literally worse than Andrew Torba.
